CREATE TABLE Department
(DepartmentID INT PRIMARY KEY,
DepartmentName VARCHAR(20))

CREATE TABLE GameDeveloper
(DevID INT PRIMARY KEY,
DevFName VARCHAR(20),
DevLName VARCHAR(20),
Salary INT,
DepartmentID INT FOREIGN KEY REFERENCES Department(DepartmentID),
)

CREATE TABLE DeveloperTeam
(TID INT PRIMARY KEY,
TName VARCHAR(20)
)

CREATE TABLE GameDevTeam
(DevID INT REFERENCES GameDeveloper(DevID),
TID INT REFERENCES DeveloperTeam(TID)
PRIMARY KEY(DevID,TID)
)

CREATE TABLE Game
(
GID INT PRIMARY KEY,
GName VARCHAR(20),
TID INT FOREIGN KEY REFERENCES DeveloperTeam(TID)
)

CREATE TABLE TesterGroup
(TGID INT PRIMARY KEY,
GroupName VARCHAR(20)
)

CREATE TABLE GameTester
(GTID INT PRIMARY KEY,
GTFName VARCHAR(20),
GTLName VARCHAR(20),
GTExperience INT,
TGID INT FOREIGN KEY REFERENCES TesterGroup(TGID)
)

CREATE TABLE TestingGame
(GTID INT REFERENCES GameTester(GTID),
GID INT REFERENCES Game(GID),
PRIMARY KEY(GTID,GID)
)

CREATE TABLE Genre
(GenreID INT PRIMARY KEY,
GenreName VARCHAR(20)
)

CREATE TABLE GameGenre
(
GID INT REFERENCES Game(GID),
GenreID INT REFERENCES Genre(GenreID)
PRIMARY KEY(GID,GenreID)
)